# Generated by Django 2.1.1 on 2020-01-08 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('patients_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=11)),
                ('phone', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('start_datetime', models.DateTimeField()),
                ('finish_datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('google_event_id', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='TableTTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('somekindofplace', models.CharField(max_length=255)),
            ],
        ),
    ]
