# Generated by Django 2.1.1 on 2020-01-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendalilio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableTTest',
        ),
    ]
