# Generated by Django 2.1.1 on 2020-01-10 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendalilio', '0003_token_google_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token_google_user',
            old_name='name',
            new_name='token',
        ),
    ]
